#!/bin/bash

function die() {
  echo ERROR "$@" >&2
  exit 1
}

PATH=/usr/bin:/usr/local/bin:$PATH
PYTHON="python"
[[ ! -x "$PYTHON" ]] || die "no python"

# wait for network
for j in {1..250};
do
  if [ $(/sbin/ping -q -c 1 google.com &>/dev/null; echo $?) != 0 ]; then
    if [ $j -gt 240 ]; then exit 1; fi # if this somehow takes longer than 20 minutes, get the hell out
    sleep 5
  else
    break
  fi
done

# ensure we have command-line tools
if [[ $(/usr/bin/xcode-select -p &>/dev/null; /bin/echo $?) == 2 ]]; then
  cmd_line_tools_temp_file="/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
  touch "$cmd_line_tools_temp_file"
  cmd_line_tools=$(softwareupdate -l | awk '/\*\ Command Line Tools/ { $1=$1;print }' | tail -1 | sed 's/^[[ \t]]*//;s/[[ \t]]*$//;s/*//' | cut -c 2-)
  softwareupdate -i "$cmd_line_tools" -v
  if [[ $(/usr/bin/xcode-select -p &>/dev/null; /bin/echo $?) != 2 ]]; then
    echo "CLT installed."
    if [[ -f "$cmd_line_tools_temp_file" ]]; then
      rm "$cmd_line_tools_temp_file"
    fi
  else
    die "CLT install failed"
  fi
fi

sleep 5

# install ansible
/usr/bin/easy_install virtualenv
/usr/local/bin/virtualenv /usr/local/gorilla/ansible
/usr/local/gorilla/ansible/bin/pip install ansible

sleep 5

# remove installer
if [ -d /usr/local/gorilla/ansible/bin/ansible ]; then
  if [ -e /usr/local/outset/everyboot-scripts/blackbackInstall ]; then
    rm /usr/local/outset/everyboot-scripts/blackbackInstall
  fi
  launchctl load /Library/LaunchDaemons/com.gorilla.blackbackRunner.plist
  rm $0
else
  die "bad Ansible install"
fi

exit 0
