#!/bin/bash

for i in {1..50};
do
  if [[ $(/sbin/ping -q -c 1 google.com &>/dev/null; /bin/echo $?) != 0 || $(/usr/bin/who | /usr/bin/grep console | /usr/bin/awk '{ print $1 }') == 'root' ]]; then
    if [ $i -gt 45 ]; then exit 1; fi
    sleep 10
  else
    break
  fi
done

if [ ! -e /usr/local/gorilla/ansible/bin/ansible ]; then
  /usr/local/gorilla/blackbackInstall
fi

PATH=/usr/local/gorilla/ansible/bin:$PATH
ansible-pull \
    --url=$1 \
    --inventory=localhost, \
    --directory=/usr/local/gorilla/blackback

exit 0
