#!/bin/bash

function die() {
  echo ERROR "$@" >&2
  exit 1
}

PATH=/usr/bin:/usr/local/bin:$PATH
PYTHON="python"
[[ ! -x "$PYTHON" ]] || die "no python"

# wait for network
for j in {1..250};
do
  if [ $(/sbin/ping -q -c 1 google.com &>/dev/null; echo $?) != 0 ]; then
    if [ $j -gt 240 ]; then exit 1; fi # if this somehow takes longer than 20 minutes, get the hell out
    sleep 5
  else
    break
  fi
done

/usr/bin/easy_install virtualenv
virtualenv /usr/local/gorilla/ansible
/usr/local/gorilla/ansible/bin/pip install ansible

if [ -d /usr/local/gorilla/ansible/bin/ansible ]; then
  if [ -e /Library/LaunchDaemons/com.gorilla.blackbackInstall.plist ]; then
    rm /Library/LaunchDaemons/com.gorilla.blackbackInstall.plist
  fi
  if [ -e /usr/local/outset/everyboot-scripts/blackbackInstall.sh ]; then
    rm /usr/local/outset/everyboot-scripts/blackbackInstall.sh
  fi
  rm /usr/local/gorilla/blackbackInstall
fi

/usr/local/gorilla/blackbackRunner

exit 0
