#!/bin/sh

cmd_line_tools_temp_file="/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
touch "$cmd_line_tools_temp_file"
cmd_line_tools=$(softwareupdate -l | awk '/\*\ Command Line Tools/ { $1=$1;print }' | tail -1 | sed 's/^[[ \t]]*//;s/[[ \t]]*$//;s/*//' | cut -c 2-)
softwareupdate -i "$cmd_line_tools" -v
if [[ -f "$cmd_line_tools_temp_file" ]]; then
  rm "$cmd_line_tools_temp_file"
fi
exit 0
